name: Build & deploy
on:
  push:
    branches:    
      - master
jobs:
  build:
    name: Building & Deploying to k8s
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: adwirawien/public-transport-information
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: repo.treescale.com
    - name: Deploy to Cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image deployment/public-transport-information public-transport-information=repo.treescale.com/adwirawien/public-transport-information:latest
    - name: Verify Deployment
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: rollout status deployment/public-transport-information
